# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_32bit
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_32bit)
  PopHead_config = debug_32bit
  Tests_config = debug_32bit
endif
ifeq ($(config),release_32bit)
  PopHead_config = release_32bit
  Tests_config = release_32bit
endif
ifeq ($(config),distribution_32bit)
  PopHead_config = distribution_32bit
  Tests_config = distribution_32bit
endif
ifeq ($(config),profiling_32bit)
  PopHead_config = profiling_32bit
  Tests_config = profiling_32bit
endif
ifeq ($(config),tests_32bit)
  PopHead_config = tests_32bit
  Tests_config = tests_32bit
endif
ifeq ($(config),debug_64bit)
  PopHead_config = debug_64bit
  Tests_config = debug_64bit
endif
ifeq ($(config),release_64bit)
  PopHead_config = release_64bit
  Tests_config = release_64bit
endif
ifeq ($(config),distribution_64bit)
  PopHead_config = distribution_64bit
  Tests_config = distribution_64bit
endif
ifeq ($(config),profiling_64bit)
  PopHead_config = profiling_64bit
  Tests_config = profiling_64bit
endif
ifeq ($(config),tests_64bit)
  PopHead_config = tests_64bit
  Tests_config = tests_64bit
endif

PROJECTS := PopHead Tests

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PopHead:
ifneq (,$(PopHead_config))
	@echo "==== Building PopHead ($(PopHead_config)) ===="
	@${MAKE} --no-print-directory -C . -f PopHead.make config=$(PopHead_config)
endif

Tests:
ifneq (,$(Tests_config))
	@echo "==== Building Tests ($(Tests_config)) ===="
	@${MAKE} --no-print-directory -C . -f Tests.make config=$(Tests_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f PopHead.make clean
	@${MAKE} --no-print-directory -C . -f Tests.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_32bit"
	@echo "  release_32bit"
	@echo "  distribution_32bit"
	@echo "  profiling_32bit"
	@echo "  tests_32bit"
	@echo "  debug_64bit"
	@echo "  release_64bit"
	@echo "  distribution_64bit"
	@echo "  profiling_64bit"
	@echo "  tests_64bit"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PopHead"
	@echo "   Tests"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"
